version: 2
jobs:
  build:
    
    working_directory: ~/backend_time


    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - restore_cache:
          key: backend_time-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: backend_time-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/test-classes
      

